---
abstract: 'Pluggable POE-powered MUD server'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: POEx-MUD
provides:
  POEx::MUD:
    file: lib/POEx/MUD.pm
    version: 0
  POEx::MUD::Backend:
    file: lib/POEx/MUD/Backend.pm
    version: 0
  POEx::MUD::Backend::Listener:
    file: lib/POEx/MUD/Backend/Listener.pm
    version: 0
  POEx::MUD::Backend::User:
    file: lib/POEx/MUD/Backend/User.pm
    version: 0
  POEx::MUD::Mobile:
    file: lib/POEx/MUD/Mobile.pm
    version: 0
  POEx::MUD::ReadWrite:
    file: lib/POEx/MUD/ReadWrite.pm
    version: 0
  POEx::MUD::ReadWrite::BDB:
    file: lib/POEx/MUD/ReadWrite/BDB.pm
    version: 0
  POEx::MUD::ReadWrite::BDB::Async:
    file: lib/POEx/MUD/ReadWrite/BDB/Async.pm
    version: 0
  POEx::MUD::ReadWrite::YAML:
    file: lib/POEx/MUD/ReadWrite/YAML.pm
    version: 0
  POEx::MUD::Server:
    file: lib/POEx/MUD/Server.pm
    version: 0
  POEx::MUD::Tools::Format:
    file: lib/POEx/MUD/Tools/Format.pm
    version: 0
  POEx::MUD::Tools::UID:
    file: lib/POEx/MUD/Tools/UID.pm
    version: 0
  POEx::MUD::Types:
    file: lib/POEx/MUD/Types.pm
    version: 0
  POEx::MUD::World:
    file: lib/POEx/MUD/World.pm
    version: 0
  POEx::MUD::World::Map:
    file: lib/POEx/MUD/World/Map.pm
    version: 0
  POEx::MUD::World::Room:
    file: lib/POEx/MUD/World/Room.pm
    version: 0
requires:
  Carp: 0
  Exporter: 0
  Module::Runtime: 0
  Moo: 1
  MooX::Role::POE::Emitter: 0.10
  MooX::Types::MooseLike: 0
  Net::IP::Minimal: 0.04
  POE: 1.3
  Socket: 2
  Try::Tiny: 0
  namespace::clean: 0.23
  perl: v5.12.1
  strictures: 1
resources:
  license: http://dev.perl.org/licenses/
version: 0
